# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import plugin_pb2 as plugin__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginHostServiceStub:
    """1. 插件宿主生命周期服务 (运行在 Host 端)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/kanon.plugin.v1.PluginHostService/Ping',
                request_serializer=plugin__pb2.PingRequest.SerializeToString,
                response_deserializer=plugin__pb2.PingResponse.FromString,
                _registered_method=True)
        self.ReloadPluginConfig = channel.unary_unary(
                '/kanon.plugin.v1.PluginHostService/ReloadPluginConfig',
                request_serializer=plugin__pb2.ReloadPluginConfigRequest.SerializeToString,
                response_deserializer=plugin__pb2.ReloadPluginConfigResponse.FromString,
                _registered_method=True)
        self.GetPluginMeta = channel.unary_unary(
                '/kanon.plugin.v1.PluginHostService/GetPluginMeta',
                request_serializer=plugin__pb2.GetPluginMetaRequest.SerializeToString,
                response_deserializer=plugin__pb2.GetPluginMetaResponse.FromString,
                _registered_method=True)
        self.InvokeAction = channel.unary_unary(
                '/kanon.plugin.v1.PluginHostService/InvokeAction',
                request_serializer=plugin__pb2.PluginActionRequest.SerializeToString,
                response_deserializer=plugin__pb2.PluginActionResponse.FromString,
                _registered_method=True)


class PluginHostServiceServicer:
    """1. 插件宿主生命周期服务 (运行在 Host 端)
    """

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadPluginConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPluginMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeAction(self, request, context):
        """Management action invoked by the control plane.

        Actions are the console counterpart of tools: credential binding, QR login and diagnostics
        are operations an operator triggers, not functions the model may call. Adapter plugins must
        expose such operations here so that their tool list stays empty — an adapter's tools would
        otherwise be offered to the LLM, which then tries to bind credentials mid-conversation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginHostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=plugin__pb2.PingRequest.FromString,
                    response_serializer=plugin__pb2.PingResponse.SerializeToString,
            ),
            'ReloadPluginConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadPluginConfig,
                    request_deserializer=plugin__pb2.ReloadPluginConfigRequest.FromString,
                    response_serializer=plugin__pb2.ReloadPluginConfigResponse.SerializeToString,
            ),
            'GetPluginMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPluginMeta,
                    request_deserializer=plugin__pb2.GetPluginMetaRequest.FromString,
                    response_serializer=plugin__pb2.GetPluginMetaResponse.SerializeToString,
            ),
            'InvokeAction': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeAction,
                    request_deserializer=plugin__pb2.PluginActionRequest.FromString,
                    response_serializer=plugin__pb2.PluginActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kanon.plugin.v1.PluginHostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kanon.plugin.v1.PluginHostService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginHostService:
    """1. 插件宿主生命周期服务 (运行在 Host 端)
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.PluginHostService/Ping',
            plugin__pb2.PingRequest.SerializeToString,
            plugin__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadPluginConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.PluginHostService/ReloadPluginConfig',
            plugin__pb2.ReloadPluginConfigRequest.SerializeToString,
            plugin__pb2.ReloadPluginConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPluginMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.PluginHostService/GetPluginMeta',
            plugin__pb2.GetPluginMetaRequest.SerializeToString,
            plugin__pb2.GetPluginMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.PluginHostService/InvokeAction',
            plugin__pb2.PluginActionRequest.SerializeToString,
            plugin__pb2.PluginActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MessagePipelineServiceStub:
    """2. 消息与事件管道服务 (运行在 Host 端，Core 主动连接各 Host 端点发起调用)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnPreFilter = channel.unary_unary(
                '/kanon.plugin.v1.MessagePipelineService/OnPreFilter',
                request_serializer=plugin__pb2.PipelineEventRequest.SerializeToString,
                response_deserializer=plugin__pb2.PreFilterResult.FromString,
                _registered_method=True)
        self.OnExecuteCommand = channel.unary_unary(
                '/kanon.plugin.v1.MessagePipelineService/OnExecuteCommand',
                request_serializer=plugin__pb2.CommandExecuteRequest.SerializeToString,
                response_deserializer=plugin__pb2.CommandExecuteResponse.FromString,
                _registered_method=True)
        self.OnCallTool = channel.unary_unary(
                '/kanon.plugin.v1.MessagePipelineService/OnCallTool',
                request_serializer=plugin__pb2.ToolCallRequest.SerializeToString,
                response_deserializer=plugin__pb2.ToolCallResponse.FromString,
                _registered_method=True)
        self.OnEvent = channel.unary_unary(
                '/kanon.plugin.v1.MessagePipelineService/OnEvent',
                request_serializer=plugin__pb2.EventNotification.SerializeToString,
                response_deserializer=plugin__pb2.EventAck.FromString,
                _registered_method=True)
        self.OnDeliverMessage = channel.unary_unary(
                '/kanon.plugin.v1.MessagePipelineService/OnDeliverMessage',
                request_serializer=plugin__pb2.DeliverMessageRequest.SerializeToString,
                response_deserializer=plugin__pb2.DeliverMessageResponse.FromString,
                _registered_method=True)
        self.OnDecorateReply = channel.unary_unary(
                '/kanon.plugin.v1.MessagePipelineService/OnDecorateReply',
                request_serializer=plugin__pb2.DecorateReplyRequest.SerializeToString,
                response_deserializer=plugin__pb2.DecorateReplyResult.FromString,
                _registered_method=True)
        self.OnPrepareTurn = channel.unary_unary(
                '/kanon.plugin.v1.MessagePipelineService/OnPrepareTurn',
                request_serializer=plugin__pb2.PrepareTurnRequest.SerializeToString,
                response_deserializer=plugin__pb2.PrepareTurnResult.FromString,
                _registered_method=True)
        self.OnLlmRequest = channel.unary_unary(
                '/kanon.plugin.v1.MessagePipelineService/OnLlmRequest',
                request_serializer=plugin__pb2.LlmRequestHookRequest.SerializeToString,
                response_deserializer=plugin__pb2.LlmRequestHookResult.FromString,
                _registered_method=True)
        self.OnHttpRequest = channel.unary_unary(
                '/kanon.plugin.v1.MessagePipelineService/OnHttpRequest',
                request_serializer=plugin__pb2.HttpRequest.SerializeToString,
                response_deserializer=plugin__pb2.HttpResponse.FromString,
                _registered_method=True)


class MessagePipelineServiceServicer:
    """2. 消息与事件管道服务 (运行在 Host 端，Core 主动连接各 Host 端点发起调用)
    """

    def OnPreFilter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnExecuteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnCallTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnEvent(self, request, context):
        """Fire-and-forget lifecycle events, sent only for the kinds a plugin lists in `PluginMeta.events`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnDeliverMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnDecorateReply(self, request, context):
        """Rewrites a reply before it is delivered; called only for plugins with
        `PluginMeta.decorates_replies`, in host priority order, each seeing the previous result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnPrepareTurn(self, request, context):
        """Adds plugin context to the current turn just before the model answers it; called only for
        plugins with `PluginMeta.prepares_turns`. The text is prepended to the current user message,
        never to the system prompt or the history, so the cached request prefix stays stable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnLlmRequest(self, request, context):
        """Rewrites the system prompt of a model conversation; called only for plugins with
        `PluginMeta.rewrites_system_prompt`, in host priority order, each seeing the previous result.
        Called once per turn before the first model request (the result is reused for the turn's
        tool rounds and its compaction), and never for a plugin's own `RequestLLM`/`RunAgent` calls
        unless they run inside the conversation.

        The system prompt is the first thing in every request, so its bytes decide the provider's
        prompt cache: a rewrite must be deterministic for a given conversation (no clocks, counters
        or per-message data — those belong in `OnPrepareTurn`). A failing or slow plugin (deadline
        as `OnPrepareTurn`) leaves the prompt as it was.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnHttpRequest(self, request, context):
        """Serves an HTTP request addressed to the plugin's web routes; called only for plugins with
        `PluginMeta.serves_http`. The management gateway forwards
        `/api/v1/plugins/<plugin_id>/http/<path>` here; the plugin routes on `path` itself.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessagePipelineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnPreFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.OnPreFilter,
                    request_deserializer=plugin__pb2.PipelineEventRequest.FromString,
                    response_serializer=plugin__pb2.PreFilterResult.SerializeToString,
            ),
            'OnExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.OnExecuteCommand,
                    request_deserializer=plugin__pb2.CommandExecuteRequest.FromString,
                    response_serializer=plugin__pb2.CommandExecuteResponse.SerializeToString,
            ),
            'OnCallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.OnCallTool,
                    request_deserializer=plugin__pb2.ToolCallRequest.FromString,
                    response_serializer=plugin__pb2.ToolCallResponse.SerializeToString,
            ),
            'OnEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.OnEvent,
                    request_deserializer=plugin__pb2.EventNotification.FromString,
                    response_serializer=plugin__pb2.EventAck.SerializeToString,
            ),
            'OnDeliverMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.OnDeliverMessage,
                    request_deserializer=plugin__pb2.DeliverMessageRequest.FromString,
                    response_serializer=plugin__pb2.DeliverMessageResponse.SerializeToString,
            ),
            'OnDecorateReply': grpc.unary_unary_rpc_method_handler(
                    servicer.OnDecorateReply,
                    request_deserializer=plugin__pb2.DecorateReplyRequest.FromString,
                    response_serializer=plugin__pb2.DecorateReplyResult.SerializeToString,
            ),
            'OnPrepareTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.OnPrepareTurn,
                    request_deserializer=plugin__pb2.PrepareTurnRequest.FromString,
                    response_serializer=plugin__pb2.PrepareTurnResult.SerializeToString,
            ),
            'OnLlmRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.OnLlmRequest,
                    request_deserializer=plugin__pb2.LlmRequestHookRequest.FromString,
                    response_serializer=plugin__pb2.LlmRequestHookResult.SerializeToString,
            ),
            'OnHttpRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.OnHttpRequest,
                    request_deserializer=plugin__pb2.HttpRequest.FromString,
                    response_serializer=plugin__pb2.HttpResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kanon.plugin.v1.MessagePipelineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kanon.plugin.v1.MessagePipelineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessagePipelineService:
    """2. 消息与事件管道服务 (运行在 Host 端，Core 主动连接各 Host 端点发起调用)
    """

    @staticmethod
    def OnPreFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.MessagePipelineService/OnPreFilter',
            plugin__pb2.PipelineEventRequest.SerializeToString,
            plugin__pb2.PreFilterResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.MessagePipelineService/OnExecuteCommand',
            plugin__pb2.CommandExecuteRequest.SerializeToString,
            plugin__pb2.CommandExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnCallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.MessagePipelineService/OnCallTool',
            plugin__pb2.ToolCallRequest.SerializeToString,
            plugin__pb2.ToolCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.MessagePipelineService/OnEvent',
            plugin__pb2.EventNotification.SerializeToString,
            plugin__pb2.EventAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnDeliverMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.MessagePipelineService/OnDeliverMessage',
            plugin__pb2.DeliverMessageRequest.SerializeToString,
            plugin__pb2.DeliverMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnDecorateReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.MessagePipelineService/OnDecorateReply',
            plugin__pb2.DecorateReplyRequest.SerializeToString,
            plugin__pb2.DecorateReplyResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnPrepareTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.MessagePipelineService/OnPrepareTurn',
            plugin__pb2.PrepareTurnRequest.SerializeToString,
            plugin__pb2.PrepareTurnResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnLlmRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.MessagePipelineService/OnLlmRequest',
            plugin__pb2.LlmRequestHookRequest.SerializeToString,
            plugin__pb2.LlmRequestHookResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnHttpRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.MessagePipelineService/OnHttpRequest',
            plugin__pb2.HttpRequest.SerializeToString,
            plugin__pb2.HttpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BotApiServiceStub:
    """3. 核心 API 服务 (运行在 Core 端，监听 core.sock / loopback，Host 主动连接调用)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterHost = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/RegisterHost',
                request_serializer=plugin__pb2.RegisterHostRequest.SerializeToString,
                response_deserializer=plugin__pb2.RegisterHostResponse.FromString,
                _registered_method=True)
        self.IngestEvent = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/IngestEvent',
                request_serializer=plugin__pb2.IngestEventRequest.SerializeToString,
                response_deserializer=plugin__pb2.IngestEventResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/SendMessage',
                request_serializer=plugin__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=plugin__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.ReplyMessage = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/ReplyMessage',
                request_serializer=plugin__pb2.DeliverMessageRequest.SerializeToString,
                response_deserializer=plugin__pb2.DeliverMessageResponse.FromString,
                _registered_method=True)
        self.RequestLLM = channel.unary_stream(
                '/kanon.plugin.v1.BotApiService/RequestLLM',
                request_serializer=plugin__pb2.LLMRequest.SerializeToString,
                response_deserializer=plugin__pb2.LLMChunk.FromString,
                _registered_method=True)
        self.CallPlatformApi = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/CallPlatformApi',
                request_serializer=plugin__pb2.PlatformApiRequest.SerializeToString,
                response_deserializer=plugin__pb2.PlatformApiResponse.FromString,
                _registered_method=True)
        self.SetStorage = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/SetStorage',
                request_serializer=plugin__pb2.SetStorageRequest.SerializeToString,
                response_deserializer=plugin__pb2.SetStorageResponse.FromString,
                _registered_method=True)
        self.GetStorage = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/GetStorage',
                request_serializer=plugin__pb2.GetStorageRequest.SerializeToString,
                response_deserializer=plugin__pb2.GetStorageResponse.FromString,
                _registered_method=True)
        self.DeleteStorage = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/DeleteStorage',
                request_serializer=plugin__pb2.DeleteStorageRequest.SerializeToString,
                response_deserializer=plugin__pb2.DeleteStorageResponse.FromString,
                _registered_method=True)
        self.ListStorage = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/ListStorage',
                request_serializer=plugin__pb2.ListStorageRequest.SerializeToString,
                response_deserializer=plugin__pb2.ListStorageResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/Ping',
                request_serializer=plugin__pb2.PingRequest.SerializeToString,
                response_deserializer=plugin__pb2.PingResponse.FromString,
                _registered_method=True)
        self.GetConversationHistory = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/GetConversationHistory',
                request_serializer=plugin__pb2.ConversationHistoryRequest.SerializeToString,
                response_deserializer=plugin__pb2.ConversationHistoryResponse.FromString,
                _registered_method=True)
        self.ListConversations = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/ListConversations',
                request_serializer=plugin__pb2.ConversationsRequest.SerializeToString,
                response_deserializer=plugin__pb2.ConversationList.FromString,
                _registered_method=True)
        self.NewConversation = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/NewConversation',
                request_serializer=plugin__pb2.ConversationsRequest.SerializeToString,
                response_deserializer=plugin__pb2.ConversationList.FromString,
                _registered_method=True)
        self.SwitchConversation = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/SwitchConversation',
                request_serializer=plugin__pb2.SelectConversationRequest.SerializeToString,
                response_deserializer=plugin__pb2.ConversationList.FromString,
                _registered_method=True)
        self.DeleteConversation = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/DeleteConversation',
                request_serializer=plugin__pb2.SelectConversationRequest.SerializeToString,
                response_deserializer=plugin__pb2.ConversationList.FromString,
                _registered_method=True)
        self.AppendConversation = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/AppendConversation',
                request_serializer=plugin__pb2.AppendConversationRequest.SerializeToString,
                response_deserializer=plugin__pb2.AppendConversationResponse.FromString,
                _registered_method=True)
        self.ListPersonas = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/ListPersonas',
                request_serializer=plugin__pb2.ListPersonasRequest.SerializeToString,
                response_deserializer=plugin__pb2.ListPersonasResponse.FromString,
                _registered_method=True)
        self.UpsertPersona = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/UpsertPersona',
                request_serializer=plugin__pb2.Persona.SerializeToString,
                response_deserializer=plugin__pb2.UpsertPersonaResponse.FromString,
                _registered_method=True)
        self.DeletePersona = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/DeletePersona',
                request_serializer=plugin__pb2.DeletePersonaRequest.SerializeToString,
                response_deserializer=plugin__pb2.DeletePersonaResponse.FromString,
                _registered_method=True)
        self.RunAgent = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/RunAgent',
                request_serializer=plugin__pb2.RunAgentRequest.SerializeToString,
                response_deserializer=plugin__pb2.RunAgentResponse.FromString,
                _registered_method=True)
        self.RefreshPluginMeta = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/RefreshPluginMeta',
                request_serializer=plugin__pb2.RefreshPluginMetaRequest.SerializeToString,
                response_deserializer=plugin__pb2.RefreshPluginMetaResponse.FromString,
                _registered_method=True)
        self.RenderImage = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/RenderImage',
                request_serializer=plugin__pb2.RenderImageRequest.SerializeToString,
                response_deserializer=plugin__pb2.RenderImageResponse.FromString,
                _registered_method=True)


class BotApiServiceServicer:
    """3. 核心 API 服务 (运行在 Core 端，监听 core.sock / loopback，Host 主动连接调用)
    """

    def RegisterHost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplyMessage(self, request, context):
        """Reply to an original platform event through the same outbound FIFO. Success
        means the platform adapter accepted delivery, not merely queue admission.
        A deadline/disconnect is an unknown outcome and must not trigger an automatic retry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestLLM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallPlatformApi(self, request, context):
        """Calls one action of a built-in adapter's platform API (OneBot action, Milky endpoint) and
        returns its result. Errors are gRPC statuses: NOT_FOUND for an unknown platform,
        UNIMPLEMENTED when the adapter offers no API, INVALID_ARGUMENT for a malformed action,
        UNAVAILABLE when the platform rejected or could not take the call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStorage(self, request, context):
        """Central key-value store, one namespace per plugin, persisted by the core in `data/kv.db`.
        Values are opaque bytes (the SDKs store JSON). A key that expired reads as absent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStorage(self, request, context):
        """Lists the plugin's live keys starting with `prefix`, sorted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Liveness probe answered by the core itself, without touching the pipeline.

        Hosts use it to notice that the core they registered with has exited: a host whose core is
        gone must stop, otherwise it keeps serving its platform (and, for adapters, keeps the
        platform's long-lived connection) while no bot instance can answer — which shows up as a
        ghost bot double-handling messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversationHistory(self, request, context):
        """Reads the model conversation an inbound message belongs to. Read-only: history is
        append-only and only the core writes it. NOT_FOUND when no enabled instance claims the
        platform, UNAVAILABLE when no model is configured, INVALID_ARGUMENT without a context.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConversations(self, request, context):
        """--- Conversations: the sessions of one chat, as `/ls`, `/new`, `/switch` and `/del` see them.
        Every call names the chat by an inbound message (`context`), resolved exactly as when the
        core answers that message. NOT_FOUND when no enabled instance claims it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewConversation(self, request, context):
        """Starts a new, empty conversation and makes it current (what `/new` does).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchConversation(self, request, context):
        """Makes another conversation of the same chat current. NOT_FOUND for an unknown session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConversation(self, request, context):
        """Deletes a conversation's history and records. Deleting the current one leaves the chat on a
        new, empty conversation. NOT_FOUND for an unknown session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendConversation(self, request, context):
        """Appends finished turns to the current conversation, e.g. a command exchange the model should
        remember. Messages must alternate user/assistant, starting with user and ending with
        assistant; anything else is INVALID_ARGUMENT. Append-only: nothing already stored changes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPersonas(self, request, context):
        """--- Personas: the operator's persona catalog (`data/personas.json`).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertPersona(self, request, context):
        """Creates or replaces a persona. INVALID_ARGUMENT for an empty id or prompt, FAILED_PRECONDITION
        for the built-in read-only persona.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePersona(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunAgent(self, request, context):
        """Runs the node's agent (model + tool loop) for a plugin and returns its final answer. Unlike
        `RequestLLM` it can use tools and can run inside a chat's conversation. UNAVAILABLE when no
        model is configured, NOT_FOUND when `context` names a chat no enabled instance claims.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshPluginMeta(self, request, context):
        """Asks the core to fetch this host's `GetPluginMeta` again, so tools, commands and triggers a
        plugin added or removed at runtime take effect for the next turn. NOT_FOUND for an unknown
        host.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenderImage(self, request, context):
        """Renders text (or SVG) into a PNG in the plugin's data directory, for sending as an image.
        INVALID_ARGUMENT for empty input or malformed SVG; UNAVAILABLE when no usable font exists.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BotApiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterHost': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterHost,
                    request_deserializer=plugin__pb2.RegisterHostRequest.FromString,
                    response_serializer=plugin__pb2.RegisterHostResponse.SerializeToString,
            ),
            'IngestEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestEvent,
                    request_deserializer=plugin__pb2.IngestEventRequest.FromString,
                    response_serializer=plugin__pb2.IngestEventResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=plugin__pb2.SendMessageRequest.FromString,
                    response_serializer=plugin__pb2.SendMessageResponse.SerializeToString,
            ),
            'ReplyMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplyMessage,
                    request_deserializer=plugin__pb2.DeliverMessageRequest.FromString,
                    response_serializer=plugin__pb2.DeliverMessageResponse.SerializeToString,
            ),
            'RequestLLM': grpc.unary_stream_rpc_method_handler(
                    servicer.RequestLLM,
                    request_deserializer=plugin__pb2.LLMRequest.FromString,
                    response_serializer=plugin__pb2.LLMChunk.SerializeToString,
            ),
            'CallPlatformApi': grpc.unary_unary_rpc_method_handler(
                    servicer.CallPlatformApi,
                    request_deserializer=plugin__pb2.PlatformApiRequest.FromString,
                    response_serializer=plugin__pb2.PlatformApiResponse.SerializeToString,
            ),
            'SetStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStorage,
                    request_deserializer=plugin__pb2.SetStorageRequest.FromString,
                    response_serializer=plugin__pb2.SetStorageResponse.SerializeToString,
            ),
            'GetStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStorage,
                    request_deserializer=plugin__pb2.GetStorageRequest.FromString,
                    response_serializer=plugin__pb2.GetStorageResponse.SerializeToString,
            ),
            'DeleteStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStorage,
                    request_deserializer=plugin__pb2.DeleteStorageRequest.FromString,
                    response_serializer=plugin__pb2.DeleteStorageResponse.SerializeToString,
            ),
            'ListStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStorage,
                    request_deserializer=plugin__pb2.ListStorageRequest.FromString,
                    response_serializer=plugin__pb2.ListStorageResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=plugin__pb2.PingRequest.FromString,
                    response_serializer=plugin__pb2.PingResponse.SerializeToString,
            ),
            'GetConversationHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversationHistory,
                    request_deserializer=plugin__pb2.ConversationHistoryRequest.FromString,
                    response_serializer=plugin__pb2.ConversationHistoryResponse.SerializeToString,
            ),
            'ListConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConversations,
                    request_deserializer=plugin__pb2.ConversationsRequest.FromString,
                    response_serializer=plugin__pb2.ConversationList.SerializeToString,
            ),
            'NewConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.NewConversation,
                    request_deserializer=plugin__pb2.ConversationsRequest.FromString,
                    response_serializer=plugin__pb2.ConversationList.SerializeToString,
            ),
            'SwitchConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchConversation,
                    request_deserializer=plugin__pb2.SelectConversationRequest.FromString,
                    response_serializer=plugin__pb2.ConversationList.SerializeToString,
            ),
            'DeleteConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConversation,
                    request_deserializer=plugin__pb2.SelectConversationRequest.FromString,
                    response_serializer=plugin__pb2.ConversationList.SerializeToString,
            ),
            'AppendConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendConversation,
                    request_deserializer=plugin__pb2.AppendConversationRequest.FromString,
                    response_serializer=plugin__pb2.AppendConversationResponse.SerializeToString,
            ),
            'ListPersonas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPersonas,
                    request_deserializer=plugin__pb2.ListPersonasRequest.FromString,
                    response_serializer=plugin__pb2.ListPersonasResponse.SerializeToString,
            ),
            'UpsertPersona': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertPersona,
                    request_deserializer=plugin__pb2.Persona.FromString,
                    response_serializer=plugin__pb2.UpsertPersonaResponse.SerializeToString,
            ),
            'DeletePersona': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePersona,
                    request_deserializer=plugin__pb2.DeletePersonaRequest.FromString,
                    response_serializer=plugin__pb2.DeletePersonaResponse.SerializeToString,
            ),
            'RunAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RunAgent,
                    request_deserializer=plugin__pb2.RunAgentRequest.FromString,
                    response_serializer=plugin__pb2.RunAgentResponse.SerializeToString,
            ),
            'RefreshPluginMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshPluginMeta,
                    request_deserializer=plugin__pb2.RefreshPluginMetaRequest.FromString,
                    response_serializer=plugin__pb2.RefreshPluginMetaResponse.SerializeToString,
            ),
            'RenderImage': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderImage,
                    request_deserializer=plugin__pb2.RenderImageRequest.FromString,
                    response_serializer=plugin__pb2.RenderImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kanon.plugin.v1.BotApiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kanon.plugin.v1.BotApiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BotApiService:
    """3. 核心 API 服务 (运行在 Core 端，监听 core.sock / loopback，Host 主动连接调用)
    """

    @staticmethod
    def RegisterHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/RegisterHost',
            plugin__pb2.RegisterHostRequest.SerializeToString,
            plugin__pb2.RegisterHostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/IngestEvent',
            plugin__pb2.IngestEventRequest.SerializeToString,
            plugin__pb2.IngestEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/SendMessage',
            plugin__pb2.SendMessageRequest.SerializeToString,
            plugin__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplyMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/ReplyMessage',
            plugin__pb2.DeliverMessageRequest.SerializeToString,
            plugin__pb2.DeliverMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestLLM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/RequestLLM',
            plugin__pb2.LLMRequest.SerializeToString,
            plugin__pb2.LLMChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallPlatformApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/CallPlatformApi',
            plugin__pb2.PlatformApiRequest.SerializeToString,
            plugin__pb2.PlatformApiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/SetStorage',
            plugin__pb2.SetStorageRequest.SerializeToString,
            plugin__pb2.SetStorageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/GetStorage',
            plugin__pb2.GetStorageRequest.SerializeToString,
            plugin__pb2.GetStorageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/DeleteStorage',
            plugin__pb2.DeleteStorageRequest.SerializeToString,
            plugin__pb2.DeleteStorageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/ListStorage',
            plugin__pb2.ListStorageRequest.SerializeToString,
            plugin__pb2.ListStorageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/Ping',
            plugin__pb2.PingRequest.SerializeToString,
            plugin__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversationHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/GetConversationHistory',
            plugin__pb2.ConversationHistoryRequest.SerializeToString,
            plugin__pb2.ConversationHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/ListConversations',
            plugin__pb2.ConversationsRequest.SerializeToString,
            plugin__pb2.ConversationList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NewConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/NewConversation',
            plugin__pb2.ConversationsRequest.SerializeToString,
            plugin__pb2.ConversationList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/SwitchConversation',
            plugin__pb2.SelectConversationRequest.SerializeToString,
            plugin__pb2.ConversationList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/DeleteConversation',
            plugin__pb2.SelectConversationRequest.SerializeToString,
            plugin__pb2.ConversationList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/AppendConversation',
            plugin__pb2.AppendConversationRequest.SerializeToString,
            plugin__pb2.AppendConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPersonas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/ListPersonas',
            plugin__pb2.ListPersonasRequest.SerializeToString,
            plugin__pb2.ListPersonasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertPersona(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/UpsertPersona',
            plugin__pb2.Persona.SerializeToString,
            plugin__pb2.UpsertPersonaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePersona(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/DeletePersona',
            plugin__pb2.DeletePersonaRequest.SerializeToString,
            plugin__pb2.DeletePersonaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/RunAgent',
            plugin__pb2.RunAgentRequest.SerializeToString,
            plugin__pb2.RunAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshPluginMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/RefreshPluginMeta',
            plugin__pb2.RefreshPluginMetaRequest.SerializeToString,
            plugin__pb2.RefreshPluginMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenderImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/RenderImage',
            plugin__pb2.RenderImageRequest.SerializeToString,
            plugin__pb2.RenderImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
