# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import plugin_pb2 as plugin__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


from ._grpc.host import (
    PluginHostServiceStub as PluginHostServiceStub,
    PluginHostServiceServicer as PluginHostServiceServicer,
    add_PluginHostServiceServicer_to_server as add_PluginHostServiceServicer_to_server,
    PluginHostService as PluginHostService,
)
from ._grpc.pipeline import (
    MessagePipelineServiceStub as MessagePipelineServiceStub,
    MessagePipelineServiceServicer as MessagePipelineServiceServicer,
    add_MessagePipelineServiceServicer_to_server as add_MessagePipelineServiceServicer_to_server,
    MessagePipelineService as MessagePipelineService,
)
from ._grpc.bot_api import (
    BotApiServiceStub as BotApiServiceStub,
    BotApiServiceServicer as BotApiServiceServicer,
    add_BotApiServiceServicer_to_server as add_BotApiServiceServicer_to_server,
)
from ._grpc.bot_experimental import (
    BotApiService as BotApiService,
)
