//! Kanon Built-in Agent Engine.
//!
//! Provides a versatile, high-performance agent runtime suitable for both
//! conversational chat bots and autonomous goal-driven task agents.
//!
//! Fully modularized:
//! - Pluggable model providers implementing [`LlmProvider`];
//! - Pluggable conversational memory implementing [`Memory`];
//! - Native in-process tools implementing [`AgentTool`] (zero IPC overhead);
//! - Dynamic cross-process tool calling via [`ToolHost`];
//! - Extensible lifecycle hooks via [`AgentHook`] for RAG, guardrails, and tracing;
//! - Standalone execution mode via [`Agent::run_standalone`].

use async_trait::async_trait;
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use kanon_proto::v1::{ToolCallRequest, tool_call_request, tool_call_response};

use crate::compaction::{COMPACTION_INSTRUCTION, CompactionPolicy, ends_cleanly, summary_block};
use crate::error::AgentError;
use crate::gateway::types::{
    ChatMessage, ChatRequest, ChatResponse, Role, TokenUsage, ToolCall, ToolDefinition,
};
use crate::gateway::{ChatChunk, ChatChunkStream, LlmProvider};
use crate::layout::{canonical_tools, normalize_request};
use crate::memory::{InMemory, Memory, MemorySnapshot};
use crate::tool_router::{
    ExecutedToolCall, ToolAttachment, ToolHost, aggregate_tools, json_to_prost_struct,
    prost_struct_to_json,
};
use dashmap::{DashMap, DashSet};
use tokio_stream::StreamExt;

/// Configuration parameters for agent reasoning and execution.
#[derive(Debug, Clone)]
pub struct AgentConfig {
    /// Maximum tool reasoning loop iterations before forcing termination.
    pub max_iterations: usize,
    /// Default model identifier.
    pub default_model: String,
    /// Name of the provider endpoint that serves `default_model`, when the node routes by name.
    ///
    /// Kept separately from `default_model` because the wire request must carry the bare upstream
    /// id while the console and the built-in `/model` command address the model as
    /// `<provider>/<model-id>`.
    pub provider: Option<String>,
    /// Maximum context window of the model in tokens, when known.
    ///
    /// Descriptive metadata: it lets the console explain why history is compacted and lets the
    /// pipeline reason about how much media fits, rather than being enforced here.
    pub context_length: Option<u32>,
    /// Optional sampling temperature.
    pub temperature: Option<f32>,
    /// Optional max tokens limit for completions.
    pub max_tokens: Option<u32>,
    /// Whether to halt immediately if a tool call returns an error.
    pub stop_on_tool_failure: bool,
    /// When a long conversation is compacted into a summary; `None` never compacts.
    ///
    /// On by default: history is append-only (see [`crate::memory`]), so without compaction a long
    /// conversation would eventually outgrow the model's context window.
    pub compaction: Option<CompactionPolicy>,
}

impl AgentConfig {
    /// Canonical `<provider>/<model-id>` reference addressed by this configuration.
    pub fn model_ref(&self) -> String {
        match self.provider.as_deref().filter(|name| !name.is_empty()) {
            Some(provider) => format!("{provider}/{}", self.default_model),
            None => self.default_model.clone(),
        }
    }
}

impl Default for AgentConfig {
    fn default() -> Self {
        Self {
            max_iterations: 5,
            default_model: "gpt-4o-mini".to_string(),
            provider: None,
            context_length: None,
            temperature: None,
            max_tokens: None,
            stop_on_tool_failure: false,
            compaction: Some(CompactionPolicy::default()),
        }
    }
}

/// Result produced after an agent run concludes.
#[derive(Debug, Clone, PartialEq)]
pub struct AgentOutput {
    /// Final natural language response generated by the agent.
    pub content: String,
    /// Sequence of tool calls executed during the reasoning loop.
    pub executed_tools: Vec<ExecutedToolCall>,
    /// Total conversational / reasoning turns executed.
    pub turns: usize,
    /// Model-reported finish reason (e.g. `stop`, `tool_calls`, `length`).
    pub finish_reason: Option<String>,
    /// Rich media produced by the executed tool calls, deduplicated in execution order.
    ///
    /// The pipeline turns these into image/file segments on the outbound message, which is how a
    /// drawing tool's output reaches the chat platform instead of only its text description.
    pub attachments: Vec<ToolAttachment>,
}

/// Pluggable tool abstraction for in-process or native agent tools.
///
/// Allows developers, internal modules, or dynamic scripts to expose functions
/// directly to the agent without requiring external gRPC IPC processes.
#[async_trait]
pub trait AgentTool: Send + Sync {
    /// Name, description, and JSON schema describing parameter expectations.
    fn definition(&self) -> ToolDefinition;

    /// Invokes the tool implementation in-process.
    async fn call(&self, session_id: &str, arguments: serde_json::Value) -> Result<String, String>;
}

/// Helper type for asynchronous native tool closures.
pub type NativeToolFn = Arc<
    dyn Fn(&str, serde_json::Value) -> Pin<Box<dyn Future<Output = Result<String, String>> + Send>>
        + Send
        + Sync,
>;

/// In-process tool constructed directly from a definition and an async closure.
pub struct NativeTool {
    definition: ToolDefinition,
    handler: NativeToolFn,
}

impl NativeTool {
    /// Creates a new native in-process tool from a definition and an async handler.
    pub fn new<F, Fut>(definition: ToolDefinition, f: F) -> Self
    where
        F: Fn(&str, serde_json::Value) -> Fut + Send + Sync + 'static,
        Fut: Future<Output = Result<String, String>> + Send + 'static,
    {
        Self {
            definition,
            handler: Arc::new(move |sid, args| Box::pin(f(sid, args))),
        }
    }
}

#[async_trait]
impl AgentTool for NativeTool {
    fn definition(&self) -> ToolDefinition {
        self.definition.clone()
    }

    async fn call(&self, session_id: &str, arguments: serde_json::Value) -> Result<String, String> {
        (self.handler)(session_id, arguments).await
    }
}

/// Lifecycle interception hooks for agent reasoning and execution.
///
/// Enables plugins and middleware to implement:
/// - RAG / semantic context retrieval injection before calling the LLM;
/// - Guardrails, safety verification, and permission confirmation before tool execution;
/// - Observability, tracing, token budget tracking, and latency auditing.
#[async_trait]
pub trait AgentHook: Send + Sync {
    /// Enriches the originating user message once, before it is appended to durable history.
    ///
    /// Runtime metadata belongs here so tool-loop requests and compaction reuse unchanged history.
    async fn on_user_message(
        &self,
        _session_id: &str,
        _message: &mut ChatMessage,
    ) -> Result<(), AgentError> {
        Ok(())
    }

    /// Invoked immediately before transmitting the request payload to the model provider.
    async fn on_llm_request(
        &self,
        _session_id: &str,
        _request: &mut ChatRequest,
    ) -> Result<(), AgentError> {
        Ok(())
    }

    /// Invoked immediately upon receiving a completion response from the model.
    async fn on_llm_response(
        &self,
        _session_id: &str,
        _response: &mut ChatResponse,
    ) -> Result<(), AgentError> {
        Ok(())
    }

    /// Invoked before dispatching a tool execution.
    ///
    /// Return `Ok(true)` to permit execution, or `Ok(false)` to veto / reject execution.
    async fn on_before_tool_call(
        &self,
        _session_id: &str,
        _call: &ToolCall,
    ) -> Result<bool, AgentError> {
        Ok(true)
    }

    /// Invoked immediately following completion of a tool execution.
    async fn on_after_tool_call(
        &self,
        _session_id: &str,
        _call: &ToolCall,
        _result: &str,
        _success: bool,
    ) -> Result<(), AgentError> {
        Ok(())
    }
}

/// Fallback host used for standalone agent executions without external gRPC plugin processes.
#[derive(Debug, Clone, Default)]
pub struct NoopHost;

#[async_trait]
#[async_trait::async_trait]
impl ToolHost for NoopHost {
    fn host_id(&self) -> &str {
        "noop"
    }

    fn plugin_metas(&self) -> Vec<kanon_proto::v1::PluginMeta> {
        Vec::new()
    }

    async fn call_tool(
        &self,
        _req: ToolCallRequest,
    ) -> Result<kanon_proto::v1::ToolCallResponse, tonic::Status> {
        Err(tonic::Status::not_found(
            "No external plugin host available",
        ))
    }
}

/// General-purpose Kanon Agent.
///
/// Encapsulates model backend, memory store, native tools, lifecycle hooks, and reasoning policies.
///
/// Cloning is cheap (every heavy part is behind an `Arc`) and is how a conversation compaction
/// outlives the turn that scheduled it: the clone shares the memory, provider and hooks.
#[derive(Clone)]
pub struct Agent {
    /// Identifier or role name of this agent.
    name: String,
    /// Static instructions placed at the top of the system block, before the persona.
    system_prompt: Option<String>,
    /// Provider backend for LLM completions.
    provider: Arc<dyn LlmProvider>,
    /// Pluggable memory backend for conversational history.
    memory: Arc<dyn Memory>,
    /// Optional session manager tracking lifecycle, turns, and metadata.
    session_manager: Option<Arc<crate::session::SessionManager>>,
    /// Optional persona registry for dynamic persona resolution.
    persona_registry: Option<Arc<crate::prompt::PersonaRegistry>>,
    /// Native in-process tools directly callable without IPC overhead.
    tools: Vec<Arc<dyn AgentTool>>,
    /// Lifecycle interception hooks.
    hooks: Vec<Arc<dyn AgentHook>>,
    /// Operational configuration.
    config: AgentConfig,
    /// Serializes compactions of one session, so an automatic one and a manual one never overlap.
    compaction_locks: Arc<DashMap<String, Arc<tokio::sync::Mutex<()>>>>,
    /// Sessions with a compaction in flight, so a burst of turns schedules one, not many.
    compacting: Arc<DashSet<String>>,
}

impl Agent {
    /// Returns a new fluent builder for constructing an [`Agent`].
    pub fn builder(name: impl Into<String>, provider: Arc<dyn LlmProvider>) -> AgentBuilder {
        AgentBuilder::new(name, provider)
    }

    /// Agent identifier name.
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Reference to the active memory backend.
    pub fn memory(&self) -> &Arc<dyn Memory> {
        &self.memory
    }

    /// Reference to the optional session manager.
    pub fn session_manager(&self) -> Option<&Arc<crate::session::SessionManager>> {
        self.session_manager.as_ref()
    }

    /// Reference to the optional persona registry.
    pub fn persona_registry(&self) -> Option<&Arc<crate::prompt::PersonaRegistry>> {
        self.persona_registry.as_ref()
    }

    /// Reference to the underlying provider.
    pub fn provider(&self) -> &Arc<dyn LlmProvider> {
        &self.provider
    }

    /// Active agent configuration.
    pub fn config(&self) -> &AgentConfig {
        &self.config
    }

    /// Registered native tools.
    pub fn tools(&self) -> &[Arc<dyn AgentTool>] {
        &self.tools
    }

    /// Registered lifecycle hooks.
    pub fn hooks(&self) -> &[Arc<dyn AgentHook>] {
        &self.hooks
    }

    /// Every tool offered to the model for one run, in the one canonical order.
    ///
    /// Native tools and plugin/MCP tools are merged and then sorted by name with sorted schema keys
    /// (see [`crate::layout`]): the tool list is the very top of the prompt, so its bytes must not
    /// depend on registration order, host start order or call frequency.
    fn collect_tools(&self, hosts: &[Arc<dyn ToolHost>]) -> Vec<ToolDefinition> {
        let mut tools: Vec<ToolDefinition> = self.tools.iter().map(|t| t.definition()).collect();
        tools.extend(aggregate_tools(hosts));
        canonical_tools(tools)
    }

    /// Builds the request for one model call, laid out static-first.
    ///
    /// The messages start as the session history (append-only). The agent's own instructions go
    /// first, hooks then add the persona and skill catalog, the conversation summary (when there is
    /// one) follows them, and [`normalize_request`] merges that whole static block into one system
    /// message. The result is `[tools] [system] [history…] [current turn]`: only the tail changes
    /// from one call to the next, so the provider serves everything before it from its prompt cache.
    async fn build_request(
        &self,
        session_id: &str,
        tools: &[ToolDefinition],
    ) -> Result<ChatRequest, AgentError> {
        let snapshot = self.memory.snapshot(session_id).await?;
        self.request_from(session_id, snapshot, tools).await
    }

    /// Builds a request from an already-read memory snapshot.
    ///
    /// Compaction reads the snapshot once and builds from it, so the messages it later folds away
    /// are exactly the ones its summary was written from.
    async fn request_from(
        &self,
        session_id: &str,
        snapshot: MemorySnapshot,
        tools: &[ToolDefinition],
    ) -> Result<ChatRequest, AgentError> {
        let MemorySnapshot { summary, messages } = snapshot;

        let mut request = ChatRequest {
            model: self.config.default_model.clone(),
            messages,
            tools: tools.to_vec(),
            temperature: self.config.temperature,
            max_tokens: self.config.max_tokens,
        };

        if let Some(prompt) = &self.system_prompt {
            request
                .messages
                .insert(0, ChatMessage::system(prompt.clone()));
        }

        // Lifecycle Hook: before LLM request (persona, skill catalog, RAG, tracing, ...)
        for hook in &self.hooks {
            hook.on_llm_request(session_id, &mut request).await?;
        }

        // The summary changes only when the history is compacted, so it sits *after* the persona
        // and skill catalog (which change less often still) and just before the history it stands in
        // for.
        if let Some(summary) = summary {
            let position = request
                .messages
                .iter()
                .take_while(|message| message.role == Role::System)
                .count();
            request
                .messages
                .insert(position, ChatMessage::system(summary_block(&summary)));
        }

        normalize_request(&mut request);
        Ok(request)
    }

    /// Returns a copy of this agent whose reasoning loop stops after `max` iterations.
    pub fn with_max_iterations(&self, max: usize) -> Agent {
        let mut agent = self.clone();
        agent.config.max_iterations = max;
        agent
    }

    /// Compacts a session's history into a summary now, whatever its size.
    ///
    /// Returns `Ok(true)` when the history was replaced by a summary, and `Ok(false)` when there was
    /// nothing to compact (too short, or not at a clean stopping point — see [`ends_cleanly`]). The
    /// tools of `hosts` are part of the summarization request so its prefix matches the
    /// conversation's own requests and the provider's cache is reused.
    pub async fn compact_session(
        &self,
        session_id: &str,
        hosts: &[Arc<dyn ToolHost>],
    ) -> Result<bool, AgentError> {
        let tools = self.collect_tools(hosts);
        self.compact(session_id, &tools).await
    }

    /// Summarizes and folds away a session's history.
    ///
    /// See [`crate::compaction`] for why the summarization request is the conversation's own request
    /// plus one appended instruction.
    async fn compact(
        &self,
        session_id: &str,
        tools: &[ToolDefinition],
    ) -> Result<bool, AgentError> {
        let lock = self
            .compaction_locks
            .entry(session_id.to_string())
            .or_default()
            .clone();
        let _guard = lock.lock().await;

        let snapshot = self.memory.snapshot(session_id).await?;
        let min_messages = self
            .config
            .compaction
            .unwrap_or_default()
            .min_messages
            .max(1);
        if snapshot.messages.len() < min_messages || !ends_cleanly(&snapshot.messages) {
            return Ok(false);
        }
        let covered = snapshot.messages.len();

        let mut request = self.request_from(session_id, snapshot, tools).await?;
        request
            .messages
            .push(ChatMessage::user(COMPACTION_INSTRUCTION));

        let mut response = self.provider.chat(&request).await?;
        for hook in &self.hooks {
            hook.on_llm_response(session_id, &mut response).await?;
        }

        // A model that ignores the instruction and asks for a tool, or answers with nothing, has
        // not produced a summary. Folding the history away on that would lose the conversation.
        let summary = response
            .content
            .as_deref()
            .map(crate::gateway::strip_reasoning_tags)
            .map(str::trim)
            .filter(|text| !text.is_empty());
        let Some(summary) = summary.filter(|_| response.tool_calls.is_empty()) else {
            return Err(AgentError::Compaction(
                "the model returned no summary (empty answer or a tool call)".to_string(),
            ));
        };

        self.memory
            .compact_history(session_id, covered, summary.to_string())
            .await?;

        tracing::info!(
            session_id = %session_id,
            compacted_messages = covered,
            summary_chars = summary.chars().count(),
            "Conversation compacted into a summary"
        );
        Ok(true)
    }

    /// Schedules a background compaction when a finished turn left the context large enough.
    ///
    /// Runs right after a reply is produced because that is when the provider's cache holds exactly
    /// the prefix the summarization request will re-send, and in the background so the user never
    /// waits for it. The size comes from the provider's own token count when it reports one (it
    /// includes the system block and tools) and from an estimate otherwise; the reply is added
    /// because it becomes part of the next request.
    fn schedule_compaction(
        &self,
        session_id: &str,
        tools: &[ToolDefinition],
        request: &ChatRequest,
        usage: Option<&TokenUsage>,
        reply: &str,
    ) {
        let Some(policy) = self.config.compaction else {
            return;
        };

        let prompt_tokens = usage
            .map(|usage| usage.prompt_tokens as usize)
            .filter(|tokens| *tokens > 0)
            .unwrap_or_else(|| crate::token::estimate_request_tokens(request));
        let reply_tokens = usage
            .map(|usage| usage.completion_tokens as usize)
            .filter(|tokens| *tokens > 0)
            .unwrap_or_else(|| crate::token::estimate_text_tokens(reply));

        if !policy.is_exceeded(prompt_tokens + reply_tokens, self.config.context_length) {
            return;
        }

        // One compaction per session at a time; a second scheduled meanwhile would only summarize
        // what the first is already summarizing.
        if !self.compacting.insert(session_id.to_string()) {
            return;
        }

        let agent = self.clone();
        let session_id = session_id.to_string();
        let tools = tools.to_vec();
        tokio::spawn(async move {
            if let Err(err) = agent.compact(&session_id, &tools).await {
                tracing::warn!(
                    session_id = %session_id,
                    error = %err,
                    "Conversation compaction failed; the history is left as it was"
                );
            }
            agent.compacting.remove(&session_id);
        });
    }

    /// Executes the agent reasoning loop for an inbound message in standalone mode,
    /// using only native registered tools (or pure conversation) without requiring gRPC hosts.
    pub async fn run_standalone(
        &self,
        session_id: &str,
        user_input: &str,
    ) -> Result<AgentOutput, AgentError> {
        self.run(session_id, user_input, &[]).await
    }

    /// Executes the agent reasoning loop for an inbound message.
    ///
    /// # Flow:
    /// 1. Initializes session system prompt if not yet set in memory;
    /// 2. Records inbound user message in memory;
    /// 3. Dynamically queries active tools from native registered tools and plugin hosts;
    /// 4. Executes reasoning loop until model emits final text or iteration ceiling is hit;
    /// 5. Invokes lifecycle hooks around LLM requests, tool authorizations, and completions;
    /// 6. Dispatches tool calls (in-process for native tools, gRPC IPC for plugin tools);
    /// 7. Stores assistant reply in memory and returns [`AgentOutput`].
    pub async fn run(
        &self,
        session_id: &str,
        user_input: &str,
        hosts: &[Arc<dyn ToolHost>],
    ) -> Result<AgentOutput, AgentError> {
        self.run_message(session_id, ChatMessage::user(user_input), hosts)
            .await
    }

    /// Executes the agent reasoning loop for a fully built user message.
    ///
    /// Identical to [`Agent::run`] except that the caller supplies the message itself, which is how
    /// a multimodal turn carrying images reaches the provider. The textual projection in
    /// [`ChatMessage::content`] is what token accounting and summaries use.
    pub async fn run_message(
        &self,
        session_id: &str,
        mut message: ChatMessage,
        hosts: &[Arc<dyn ToolHost>],
    ) -> Result<AgentOutput, AgentError> {
        for hook in &self.hooks {
            hook.on_user_message(session_id, &mut message).await?;
        }
        let user_input = message.content.clone().unwrap_or_default();

        // 1. Push user message to memory
        self.memory.push_message(session_id, message).await?;

        // 2. Dynamically aggregate tools from both native tools and active plugin hosts
        let tools = self.collect_tools(hosts);

        let mut executed_tools = Vec::new();
        let mut attachments: Vec<ToolAttachment> = Vec::new();
        let mut iterations = 0;

        // 3. Reasoning and tool execution loop
        loop {
            let request = self.build_request(session_id, &tools).await?;

            let mut response = self.provider.chat(&request).await?;

            // Recover tool calls a model emitted as text markup instead of structured calls, so the
            // loop executes them instead of sending the markup to the chat platform as an answer.
            normalize_textual_tool_calls(&mut response);

            // Lifecycle Hook: after LLM response (e.g. for auditing / token counting)
            for hook in &self.hooks {
                hook.on_llm_response(session_id, &mut response).await?;
            }

            // Terminal state: Model completed generation without requesting tools
            if response.tool_calls.is_empty() {
                let final_content = response.content.unwrap_or_default();
                if !final_content.is_empty() {
                    self.memory
                        .push_message(session_id, ChatMessage::assistant(&final_content))
                        .await?;
                }

                if let Some(ref sm) = self.session_manager {
                    let tokens_used = response
                        .usage
                        .as_ref()
                        .map(|u| u.total_tokens as usize)
                        .unwrap_or_else(|| {
                            crate::token::estimate_text_tokens(&user_input)
                                + crate::token::estimate_text_tokens(&final_content)
                        });
                    sm.record_turn(session_id, tokens_used);
                }

                self.schedule_compaction(
                    session_id,
                    &tools,
                    &request,
                    response.usage.as_ref(),
                    &final_content,
                );

                return Ok(AgentOutput {
                    content: final_content,
                    executed_tools,
                    turns: iterations + 1,
                    finish_reason: response.finish_reason,
                    attachments,
                });
            }

            // Guard against runaway loop recursion
            if iterations >= self.config.max_iterations {
                tracing::warn!(
                    agent = %self.name,
                    session_id = %session_id,
                    iterations = iterations,
                    "Agent reasoning iteration ceiling reached; breaking loop"
                );
                let fallback = response.content.unwrap_or_else(|| {
                    "Agent reasoning recursion limit reached; execution terminated.".to_string()
                });
                self.memory
                    .push_message(session_id, ChatMessage::assistant(&fallback))
                    .await?;

                if let Some(ref sm) = self.session_manager {
                    let tokens_used = crate::token::estimate_text_tokens(&user_input)
                        + crate::token::estimate_text_tokens(&fallback);
                    sm.record_turn(session_id, tokens_used);
                }

                self.schedule_compaction(session_id, &tools, &request, None, &fallback);

                return Ok(AgentOutput {
                    content: fallback,
                    executed_tools,
                    turns: iterations + 1,
                    finish_reason: Some("max_iterations".to_string()),
                    attachments,
                });
            }

            iterations += 1;

            // Record assistant tool calls turn into history
            self.memory
                .push_message(
                    session_id,
                    ChatMessage {
                        role: Role::Assistant,
                        content: response.content.clone(),
                        parts: None,
                        tool_calls: Some(response.tool_calls.clone()),
                        tool_call_id: None,
                        name: None,
                    },
                )
                .await?;

            // Execute each requested tool call
            for call in response.tool_calls {
                // Hook: tool call permission / safety check
                let mut permitted = true;
                for hook in &self.hooks {
                    if !hook.on_before_tool_call(session_id, &call).await? {
                        permitted = false;
                        break;
                    }
                }
                if !permitted {
                    tracing::info!(agent = %self.name, tool = %call.name, "Tool call was vetoed by agent hook");
                    let veto_msg =
                        format!("Tool '{}' execution was denied by agent policy", call.name);
                    self.memory
                        .push_message(session_id, ChatMessage::tool_response(&call.id, &veto_msg))
                        .await?;
                    executed_tools.push(ExecutedToolCall {
                        call_id: call.id,
                        tool_name: call.name.clone(),
                        plugin_id: "policy".to_string(),
                        host_id: "agent_hook".to_string(),
                        success: false,
                    });
                    continue;
                }

                // Branch A: Check registered native in-process tools
                if let Some(native_tool) =
                    self.tools.iter().find(|t| t.definition().name == call.name)
                {
                    tracing::debug!(agent = %self.name, tool = %call.name, "Executing native tool in-process");
                    let (result_str, is_success) =
                        match native_tool.call(session_id, call.arguments.clone()).await {
                            Ok(res) => (res, true),
                            Err(err) => (format!("Error: {err}"), false),
                        };

                    executed_tools.push(ExecutedToolCall {
                        call_id: call.id.clone(),
                        tool_name: call.name.clone(),
                        plugin_id: "native".to_string(),
                        host_id: "in_process".to_string(),
                        success: is_success,
                    });

                    for hook in &self.hooks {
                        hook.on_after_tool_call(session_id, &call, &result_str, is_success)
                            .await?;
                    }

                    self.memory
                        .push_message(
                            session_id,
                            ChatMessage::tool_response(&call.id, &result_str),
                        )
                        .await?;

                    if !is_success && self.config.stop_on_tool_failure {
                        return Err(AgentError::Memory(format!(
                            "Native tool '{}' failed: {result_str}",
                            call.name
                        )));
                    }
                    continue;
                }

                // Branch B: Resolve tool on external gRPC plugin hosts
                let target = find_tool_target(&call.name, hosts);

                let (target_host, plugin_id, actual_tool_name) = match target {
                    Some((h, pid, tname)) => (h, pid, tname),
                    None => {
                        tracing::warn!(tool = %call.name, "Requested tool not declared by any native tool or active host");
                        let err_msg = format!("Tool '{}' not registered", call.name);
                        self.memory
                            .push_message(
                                session_id,
                                ChatMessage::tool_response(&call.id, &err_msg),
                            )
                            .await?;
                        executed_tools.push(ExecutedToolCall {
                            call_id: call.id,
                            tool_name: call.name.clone(),
                            plugin_id: "unknown".to_string(),
                            host_id: "unknown".to_string(),
                            success: false,
                        });
                        if self.config.stop_on_tool_failure {
                            return Err(AgentError::ToolNotFound(call.name));
                        }
                        continue;
                    }
                };

                // Zero-copy in-memory translation from serde_json::Value to prost_types::Struct
                let structured_args = match &call.arguments {
                    serde_json::Value::Object(_) => json_to_prost_struct(&call.arguments),
                    _ => None,
                };

                let tool_req = ToolCallRequest {
                    call_id: call.id.clone(),
                    tool_name: actual_tool_name,
                    session_id: session_id.to_string(),
                    payload: structured_args.map(tool_call_request::Payload::StructuredArgs),
                    // The host attaches the platform event of the turn; the agent never knew it.
                    context: None,
                };

                tracing::debug!(
                    agent = %self.name,
                    tool = %call.name,
                    host_id = %target_host.host_id(),
                    plugin_id = %plugin_id,
                    "Agent dispatching tool RPC to host"
                );

                match target_host.call_tool(tool_req).await {
                    Ok(resp) => {
                        let is_success = resp.success;
                        executed_tools.push(ExecutedToolCall {
                            call_id: call.id.clone(),
                            tool_name: call.name.clone(),
                            plugin_id: plugin_id.clone(),
                            host_id: target_host.host_id().to_string(),
                            success: is_success,
                        });

                        // Attachment paths are delivery metadata, not conversation content: they are
                        // collected here so the textual result can be redacted below. A filesystem
                        // path must never reach the model (or the transcript) through the tool result.
                        let redactions: Vec<String> = resp
                            .attachments
                            .iter()
                            .filter_map(|attachment| attachment.file_path.clone())
                            .collect();

                        // Attachments of a failed call are discarded with it: a partial image from
                        // an errored tool would be sent to the user as if it were a result.
                        if is_success {
                            for attachment in resp.attachments {
                                let attachment = ToolAttachment::from_proto(attachment);
                                if !attachments.contains(&attachment) {
                                    attachments.push(attachment);
                                }
                            }
                        }

                        let result_str = if !is_success {
                            format!("Error: {}", resp.error_message)
                        } else {
                            match resp.payload {
                                Some(tool_call_response::Payload::StructuredResult(s)) => {
                                    prost_struct_to_json(s).to_string()
                                }
                                Some(tool_call_response::Payload::RawBytes(bytes)) => {
                                    String::from_utf8_lossy(&bytes).to_string()
                                }
                                None => "{}".to_string(),
                            }
                        };
                        let result_str = redact_tool_paths(result_str, &redactions);

                        for hook in &self.hooks {
                            hook.on_after_tool_call(session_id, &call, &result_str, is_success)
                                .await?;
                        }

                        self.memory
                            .push_message(
                                session_id,
                                ChatMessage::tool_response(&call.id, result_str),
                            )
                            .await?;

                        if !is_success && self.config.stop_on_tool_failure {
                            tracing::warn!(tool = %call.name, "Tool reported failure and stop_on_tool_failure is enabled");
                            break;
                        }
                    }
                    Err(status) => {
                        tracing::error!(tool = %call.name, error = %status, "Tool RPC execution failed");
                        executed_tools.push(ExecutedToolCall {
                            call_id: call.id.clone(),
                            tool_name: call.name.clone(),
                            plugin_id: plugin_id.clone(),
                            host_id: target_host.host_id().to_string(),
                            success: false,
                        });

                        self.memory
                            .push_message(
                                session_id,
                                ChatMessage::tool_response(
                                    &call.id,
                                    format!("RPC Error: {}", status.message()),
                                ),
                            )
                            .await?;

                        if self.config.stop_on_tool_failure {
                            return Err(AgentError::from(status));
                        }
                    }
                }
            }
        }
    }

    /// Executes the agent reasoning loop in standalone streaming mode, returning incremental chunks
    /// for the assistant's final response.
    ///
    /// If tool execution turns are required, they are executed internally before streaming
    /// the final text response. Upon stream completion, the full assistant message is
    /// committed into session memory.
    pub async fn run_standalone_stream(
        &self,
        session_id: &str,
        user_input: &str,
    ) -> Result<ChatChunkStream, AgentError> {
        self.run_stream(session_id, user_input, &[]).await
    }

    /// Executes the agent reasoning loop with tool resolution, streaming the final assistant response.
    pub async fn run_stream(
        &self,
        session_id: &str,
        user_input: &str,
        hosts: &[Arc<dyn ToolHost>],
    ) -> Result<ChatChunkStream, AgentError> {
        // Enrich only the originating message; request hooks must not fabricate later turns.
        let mut message = ChatMessage::user(user_input);
        for hook in &self.hooks {
            hook.on_user_message(session_id, &mut message).await?;
        }
        self.memory.push_message(session_id, message).await?;

        // 2. Dynamically aggregate tools
        let tools = self.collect_tools(hosts);

        let mut iterations = 0;

        // If tools are available, execute intermediate tool turns first
        while !tools.is_empty() && iterations < self.config.max_iterations {
            let request = self.build_request(session_id, &tools).await?;

            let mut response = self.provider.chat(&request).await?;

            for hook in &self.hooks {
                hook.on_llm_response(session_id, &mut response).await?;
            }

            // If no tools were called, this is the final response
            if response.tool_calls.is_empty() {
                let final_content = response.content.unwrap_or_default();
                if !final_content.is_empty() {
                    self.memory
                        .push_message(session_id, ChatMessage::assistant(&final_content))
                        .await?;
                }
                let (tx, rx) = tokio::sync::mpsc::channel(2);
                let _ = tx.send(Ok(ChatChunk::delta(&final_content))).await;
                let _ = tx.send(Ok(ChatChunk::done(response.finish_reason))).await;
                return Ok(Box::pin(tokio_stream::wrappers::ReceiverStream::new(rx)));
            }

            // Otherwise, execute tools
            iterations += 1;
            self.memory
                .push_message(
                    session_id,
                    ChatMessage {
                        role: Role::Assistant,
                        content: response.content.clone(),
                        parts: None,
                        tool_calls: Some(response.tool_calls.clone()),
                        tool_call_id: None,
                        name: None,
                    },
                )
                .await?;

            for call in response.tool_calls {
                let mut permitted = true;
                for hook in &self.hooks {
                    if !hook.on_before_tool_call(session_id, &call).await? {
                        permitted = false;
                        break;
                    }
                }
                if !permitted {
                    let veto_msg =
                        format!("Tool '{}' execution was denied by agent policy", call.name);
                    self.memory
                        .push_message(session_id, ChatMessage::tool_response(&call.id, &veto_msg))
                        .await?;
                    continue;
                }

                if let Some(native_tool) =
                    self.tools.iter().find(|t| t.definition().name == call.name)
                {
                    let (result_str, is_success) =
                        match native_tool.call(session_id, call.arguments.clone()).await {
                            Ok(res) => (res, true),
                            Err(err) => (format!("Error: {err}"), false),
                        };
                    for hook in &self.hooks {
                        hook.on_after_tool_call(session_id, &call, &result_str, is_success)
                            .await?;
                    }
                    self.memory
                        .push_message(
                            session_id,
                            ChatMessage::tool_response(&call.id, &result_str),
                        )
                        .await?;
                    continue;
                }

                let target = find_tool_target(&call.name, hosts);
                let (target_host, plugin_id, actual_tool_name) = match target {
                    Some((h, pid, tname)) => (h, pid, tname),
                    None => {
                        let err_msg = format!("Tool '{}' not registered", call.name);
                        self.memory
                            .push_message(
                                session_id,
                                ChatMessage::tool_response(&call.id, &err_msg),
                            )
                            .await?;
                        continue;
                    }
                };

                let structured_args = match &call.arguments {
                    serde_json::Value::Object(_) => json_to_prost_struct(&call.arguments),
                    _ => None,
                };
                let tool_req = ToolCallRequest {
                    call_id: call.id.clone(),
                    tool_name: actual_tool_name,
                    session_id: session_id.to_string(),
                    payload: structured_args.map(tool_call_request::Payload::StructuredArgs),
                    // The host attaches the platform event of the turn; the agent never knew it.
                    context: None,
                };

                tracing::debug!(
                    agent = %self.name,
                    tool = %call.name,
                    host_id = %target_host.host_id(),
                    plugin_id = %plugin_id,
                    "Agent stream dispatching tool RPC to host"
                );

                match target_host.call_tool(tool_req).await {
                    Ok(resp) => {
                        let is_success = resp.success;
                        let redactions: Vec<String> = resp
                            .attachments
                            .iter()
                            .filter_map(|attachment| attachment.file_path.clone())
                            .collect();
                        let result_str = if !is_success {
                            format!("Error: {}", resp.error_message)
                        } else {
                            match resp.payload {
                                Some(tool_call_response::Payload::StructuredResult(s)) => {
                                    prost_struct_to_json(s).to_string()
                                }
                                Some(tool_call_response::Payload::RawBytes(bytes)) => {
                                    String::from_utf8_lossy(&bytes).to_string()
                                }
                                None => "{}".to_string(),
                            }
                        };
                        let result_str = redact_tool_paths(result_str, &redactions);
                        for hook in &self.hooks {
                            hook.on_after_tool_call(session_id, &call, &result_str, is_success)
                                .await?;
                        }
                        self.memory
                            .push_message(
                                session_id,
                                ChatMessage::tool_response(&call.id, result_str),
                            )
                            .await?;
                    }
                    Err(st) => {
                        let err_msg = format!("Tool RPC failed: {st}");
                        self.memory
                            .push_message(
                                session_id,
                                ChatMessage::tool_response(&call.id, &err_msg),
                            )
                            .await?;
                    }
                }
            }
        }

        // Final streaming generation turn (pure assistant reply). It deliberately offers no tools:
        // a stream cannot carry tool calls, so this turn must answer in text. That reshapes the
        // top of the prompt, which is acceptable only because it is the exceptional path taken
        // when no tools exist or the tool loop ran out of iterations.
        let request = self.build_request(session_id, &[]).await?;

        let inner_stream = self.provider.chat_stream(&request).await?;
        let (tx, rx) = tokio::sync::mpsc::channel(32);
        let memory = self.memory.clone();
        let sid = session_id.to_string();
        let sm_opt = self.session_manager.clone();
        let hooks = self.hooks.clone();
        let user_toks = crate::token::estimate_text_tokens(user_input);

        tokio::spawn(async move {
            let mut inner = inner_stream;
            let mut accumulated = String::new();

            while let Some(chunk_res) = inner.next().await {
                match chunk_res {
                    Ok(chunk) => {
                        accumulated.push_str(&chunk.delta_text);
                        let is_fin = chunk.is_finished;
                        let fin_reason = chunk.finish_reason.clone();
                        let _ = tx.send(Ok(chunk)).await;
                        if is_fin {
                            if !accumulated.is_empty()
                                && let Err(e) = memory
                                    .push_message(&sid, ChatMessage::assistant(&accumulated))
                                    .await
                            {
                                tracing::error!(session_id = %sid, error = %e, "Failed to persist streaming assistant response to memory");
                            }
                            if let Some(ref sm) = sm_opt {
                                let tokens =
                                    user_toks + crate::token::estimate_text_tokens(&accumulated);
                                sm.record_turn(&sid, tokens);
                            }
                            let mut resp = crate::gateway::ChatResponse {
                                content: if accumulated.is_empty() {
                                    None
                                } else {
                                    Some(accumulated.clone())
                                },
                                tool_calls: Vec::new(),
                                finish_reason: fin_reason,
                                usage: None,
                            };
                            for hook in &hooks {
                                let _ = hook.on_llm_response(&sid, &mut resp).await;
                            }
                            return;
                        }
                    }
                    Err(e) => {
                        let _ = tx.send(Err(e)).await;
                        return;
                    }
                }
            }

            if !accumulated.is_empty()
                && let Err(e) = memory
                    .push_message(&sid, ChatMessage::assistant(&accumulated))
                    .await
            {
                tracing::error!(session_id = %sid, error = %e, "Failed to persist streaming assistant response to memory");
            }
            if let Some(ref sm) = sm_opt {
                let tokens = user_toks + crate::token::estimate_text_tokens(&accumulated);
                sm.record_turn(&sid, tokens);
            }
            let mut resp = crate::gateway::ChatResponse {
                content: if accumulated.is_empty() {
                    None
                } else {
                    Some(accumulated.clone())
                },
                tool_calls: Vec::new(),
                finish_reason: None,
                usage: None,
            };
            for hook in &hooks {
                let _ = hook.on_llm_response(&sid, &mut resp).await;
            }
        });

        Ok(Box::pin(tokio_stream::wrappers::ReceiverStream::new(rx)))
    }
}

/// Removes tool-produced filesystem paths from a tool result before it enters memory.
///
/// A tool that generated a file reports the attachment (which the pipeline delivers to the platform)
/// and, very often, the path in its textual result. The path is node-internal: leaving it in the
/// transcript leaks an absolute location to the model and to anyone reading the console, so it is
/// replaced by a marker — the file itself is still sent.
fn redact_tool_paths(mut text: String, paths: &[String]) -> String {
    for path in paths {
        let trimmed = path.trim();
        if !trimmed.is_empty() && text.contains(trimmed) {
            text = text.replace(trimmed, "[attachment]");
        }
    }
    text
}

/// Recovers tool calls from a completion whose model emitted markup instead of a structured array.
///
/// Some endpoints ignore the `tools` request field and answer with `<tool_call>...` text. Turning
/// that text back into real calls is what makes the reasoning loop execute the tool and continue;
/// without it the markup is returned to the user as the assistant's answer.
fn normalize_textual_tool_calls(response: &mut ChatResponse) {
    if !response.tool_calls.is_empty() {
        return;
    }
    let Some(content) = response.content.as_deref() else {
        return;
    };

    let (recovered, cleaned) = crate::tool_call_text::extract_textual_tool_calls(content);
    if recovered.is_empty() {
        return;
    }

    tracing::info!(
        tool_calls = recovered.len(),
        tools = ?recovered.iter().map(|call| call.name.as_str()).collect::<Vec<_>>(),
        "Recovered tool calls a model emitted as text markup"
    );

    response.tool_calls = recovered;
    response.content = if cleaned.trim().is_empty() {
        None
    } else {
        Some(cleaned)
    };
}

/// Helper locating the owning host, plugin ID, and canonical tool name for an invoked tool name.
///
/// Resolves both:
/// 1. Canonical namespaced names (`<sanitized_plugin_id>__<tool_name>`).
/// 2. Bare tool names (`<tool_name>`), provided there is exactly one matching plugin.
///
/// If multiple plugins offer the same bare name and an ambiguous invocation is received,
/// returns `None` and logs an error to prevent silent, non-deterministic routing.
fn find_tool_target(
    tool_name: &str,
    hosts: &[Arc<dyn ToolHost>],
) -> Option<(Arc<dyn ToolHost>, String, String)> {
    // 1. Check for exact namespaced match first: <plugin_id>__<tool_name>
    for host in hosts {
        let metas = host.plugin_metas();
        for plugin in &metas {
            let prefix = format!(
                "{}__{}",
                crate::tool_router::sanitize_tool_identifier(&plugin.id),
                ""
            );
            if tool_name.starts_with(&prefix) {
                let base_name = &tool_name[prefix.len()..];
                for tool in &plugin.tools {
                    if tool.name == base_name {
                        return Some((host.clone(), plugin.id.clone(), tool.name.clone()));
                    }
                }
            }
        }
    }

    // 2. Search for bare tool name across all plugins
    let mut matches = Vec::new();
    for host in hosts {
        let metas = host.plugin_metas();
        for plugin in &metas {
            for tool in &plugin.tools {
                if tool.name == tool_name {
                    matches.push((host.clone(), plugin.id.clone(), tool.name.clone()));
                }
            }
        }
    }

    if matches.len() == 1 {
        Some(matches.remove(0))
    } else if matches.len() > 1 {
        tracing::error!(
            tool_name = %tool_name,
            match_count = matches.len(),
            "Ambiguous tool invocation: multiple plugins declare '{}'; invoke via namespaced name",
            tool_name
        );
        None
    } else {
        None
    }
}

/// Fluent builder for constructing customizable [`Agent`] instances.
pub struct AgentBuilder {
    name: String,
    system_prompt: Option<String>,
    provider: Arc<dyn LlmProvider>,
    memory: Option<Arc<dyn Memory>>,
    session_manager: Option<Arc<crate::session::SessionManager>>,
    persona_registry: Option<Arc<crate::prompt::PersonaRegistry>>,
    tools: Vec<Arc<dyn AgentTool>>,
    hooks: Vec<Arc<dyn AgentHook>>,
    config: AgentConfig,
}

impl AgentBuilder {
    /// Initiates a new builder with the agent name and backend model provider.
    pub fn new(name: impl Into<String>, provider: Arc<dyn LlmProvider>) -> Self {
        Self {
            name: name.into(),
            system_prompt: None,
            provider,
            memory: None,
            session_manager: None,
            persona_registry: None,
            tools: Vec::new(),
            hooks: Vec::new(),
            config: AgentConfig::default(),
        }
    }

    /// Sets the base persona / system prompt for the agent.
    pub fn system_prompt(mut self, prompt: impl Into<String>) -> Self {
        self.system_prompt = Some(prompt.into());
        self
    }

    /// Injects a custom memory backend (e.g. SQLite, Redis, or custom plugin memory).
    pub fn memory(mut self, memory: Arc<dyn Memory>) -> Self {
        self.memory = Some(memory);
        self
    }

    /// Injects a session manager for metadata, multi-scope keys, and turn lifecycle tracking.
    pub fn session_manager(mut self, manager: Arc<crate::session::SessionManager>) -> Self {
        self.session_manager = Some(manager);
        self
    }

    /// Injects a persona registry for dynamic persona resolution.
    pub fn persona_registry(mut self, registry: Arc<crate::prompt::PersonaRegistry>) -> Self {
        self.persona_registry = Some(registry);
        self
    }

    /// Registers a native in-process tool on this agent.
    pub fn tool(mut self, tool: impl AgentTool + 'static) -> Self {
        self.tools.push(Arc::new(tool));
        self
    }

    /// Registers a native in-process tool wrapped in an [`Arc`].
    pub fn tool_arc(mut self, tool: Arc<dyn AgentTool>) -> Self {
        self.tools.push(tool);
        self
    }

    /// Registers a lifecycle interception hook on this agent.
    pub fn hook(mut self, hook: impl AgentHook + 'static) -> Self {
        self.hooks.push(Arc::new(hook));
        self
    }

    /// Registers a lifecycle hook wrapped in an [`Arc`].
    pub fn hook_arc(mut self, hook: Arc<dyn AgentHook>) -> Self {
        self.hooks.push(hook);
        self
    }

    /// Sets default model tag.
    pub fn model(mut self, model: impl Into<String>) -> Self {
        self.config.default_model = model.into();
        self
    }

    /// Names the provider endpoint that serves the default model.
    pub fn provider(mut self, provider: Option<String>) -> Self {
        self.config.provider = provider;
        self
    }

    /// Records the default model's context window, when known.
    pub fn context_length(mut self, context_length: Option<u32>) -> Self {
        self.config.context_length = context_length;
        self
    }

    /// Sets maximum reasoning iterations (default 5).
    pub fn max_iterations(mut self, max: usize) -> Self {
        self.config.max_iterations = max;
        self
    }

    /// Sets sampling temperature.
    pub fn temperature(mut self, temp: f32) -> Self {
        self.config.temperature = Some(temp);
        self
    }

    /// Sets max tokens.
    pub fn max_tokens(mut self, tokens: u32) -> Self {
        self.config.max_tokens = Some(tokens);
        self
    }

    /// Configures whether to stop immediately if a tool fails.
    pub fn stop_on_tool_failure(mut self, stop: bool) -> Self {
        self.config.stop_on_tool_failure = stop;
        self
    }

    /// Sets when long conversations are compacted into a summary; `None` never compacts.
    pub fn compaction(mut self, policy: Option<CompactionPolicy>) -> Self {
        self.config.compaction = policy;
        self
    }

    /// Builds the configured [`Agent`].
    pub fn build(mut self) -> Agent {
        let memory = self
            .memory
            .or_else(|| self.session_manager.as_ref().map(|sm| sm.memory().clone()))
            .unwrap_or_else(|| Arc::new(InMemory::new()));

        if let Some(ref session_mgr) = self.session_manager
            && let Some(ref persona_reg) = self.persona_registry
        {
            // The persona hook puts the persona at the very top of the system block. Registered
            // first, it runs before every other hook, so hooks that append context (the skill
            // catalog, RAG, ...) always land after it.
            self.hooks.insert(
                0,
                Arc::new(crate::prompt::PersonaHook::new(
                    session_mgr.clone(),
                    persona_reg.clone(),
                )),
            );
        }

        Agent {
            name: self.name,
            system_prompt: self.system_prompt,
            provider: self.provider,
            memory,
            session_manager: self.session_manager,
            persona_registry: self.persona_registry,
            tools: self.tools,
            hooks: self.hooks,
            config: self.config,
            compaction_locks: Arc::new(DashMap::new()),
            compacting: Arc::new(DashSet::new()),
        }
    }
}
