//! Cross-language Tool Calling state machine router and execution loop.
//!
//! Bridges LLM function calling with out-of-process plugin hosts via gRPC.
//! Dynamically aggregates tool definitions from active plugin hosts, translates
//! arguments between `prost_types::Struct` and `serde_json::Value` without
//! redundant string serialization, dispatches tool execution over IPC, and feeds
//! execution results back to the model with loop recursion protection.

use async_trait::async_trait;
use std::sync::Arc;

use kanon_proto::v1::{PluginMeta, ToolCallRequest, ToolCallResponse};

pub use kanon_proto::json::{
    json_to_prost_struct, json_to_prost_value, prost_struct_to_json, prost_value_to_json,
};

use crate::agent::Agent;
use crate::builtin::BuiltinAgent;
use crate::error::{AgentError, ToolRouterError};
use crate::gateway::LlmProvider;
use crate::gateway::types::ToolDefinition;
use crate::memory::Memory;

/// Abstract interface for a plugin host capable of executing tool calls.
///
/// Implemented by `ManagedHost` in `kanon-core` and mock hosts in unit tests.
#[async_trait]
pub trait ToolHost: Send + Sync {
    /// Unique identifier of the host process (e.g. `host_demo_rust`).
    fn host_id(&self) -> &str;

    /// Metadata descriptors of all plugins (or MCP servers) reachable through this host.
    ///
    /// Returned by value: a host whose tool list is refreshed at runtime (an MCP server whose
    /// connection is re-established) cannot hand out a borrowed slice of lock-guarded state.
    fn plugin_metas(&self) -> Vec<PluginMeta>;

    /// Invokes a declared tool on this host via gRPC IPC.
    async fn call_tool(&self, req: ToolCallRequest) -> Result<ToolCallResponse, tonic::Status>;
}

/// Rich media produced by a tool call, ready to be attached to an outbound message.
///
/// Kept free of the protobuf type on purpose: the pipeline reasons about "an image to send", not
/// about the wire representation a plugin host happened to use.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ToolAttachment {
    /// MIME type of the payload (e.g. `image/png`).
    pub mime_type: String,
    /// Absolute path of a file holding the bytes, when the core materialized them.
    pub file_path: Option<String>,
    /// Remote URL, when the tool referenced one instead of embedding bytes.
    pub url: Option<String>,
}

impl ToolAttachment {
    /// Converts the wire representation into the domain type.
    pub fn from_proto(proto: kanon_proto::v1::ToolAttachment) -> Self {
        Self {
            mime_type: proto.mime_type,
            file_path: proto.file_path,
            url: proto.url,
        }
    }

    /// Converts the domain type into its wire representation.
    pub fn to_proto(&self) -> kanon_proto::v1::ToolAttachment {
        kanon_proto::v1::ToolAttachment {
            mime_type: self.mime_type.clone(),
            file_path: self.file_path.clone(),
            url: self.url.clone(),
        }
    }
}

/// Record of an executed tool call, useful for audit logging and verification.
#[derive(Debug, Clone, PartialEq)]
pub struct ExecutedToolCall {
    /// Unique call identifier allocated by the provider.
    pub call_id: String,
    /// Function name of the tool called.
    pub tool_name: String,
    /// Plugin identifier hosting the tool.
    pub plugin_id: String,
    /// Host process identifier running the plugin.
    pub host_id: String,
    /// Execution status returned by the tool handler.
    pub success: bool,
}

/// Output produced by the tool router execution loop.
#[derive(Debug, Clone, PartialEq)]
pub struct ToolRouterOutput {
    /// Final natural language response generated by the model.
    pub content: String,
    /// Model reasoning for this turn, kept apart from `content` (see [`crate::agent::AgentOutput`]).
    pub reasoning: Option<String>,
    /// Audit sequence of all tool calls executed across reasoning turns.
    pub executed_tools: Vec<ExecutedToolCall>,
    /// Rich media produced by those tool calls, in execution order.
    pub attachments: Vec<ToolAttachment>,
}

/// Sanitizes a plugin identifier so it is compliant with model tool naming constraints.
/// Both OpenAI and Anthropic require tool names to adhere to `^[a-zA-Z0-9_-]{1,64}$`.
pub fn sanitize_tool_identifier(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' || c == '-' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// Constructs the canonical namespaced tool name for a plugin tool:
/// `<sanitized_plugin_id>__<tool_name>`
pub fn namespaced_tool_name(plugin_id: &str, tool_name: &str) -> String {
    format!("{}__{}", sanitize_tool_identifier(plugin_id), tool_name)
}

/// One tool definition together with the provider it came from.
///
/// The management gateway needs the attribution to show an operator *where* a tool comes from;
/// [`aggregate_tools`] deliberately drops it because the model only needs the definition.
#[derive(Debug, Clone, PartialEq)]
pub struct ResolvedTool {
    /// Definition exactly as it is presented to the model.
    pub definition: ToolDefinition,
    /// Plugin (or MCP server host) identifier declaring the tool.
    pub plugin_id: String,
    /// Host process exposing the tool.
    pub host_id: String,
    /// Original host-local name, before any model-facing collision namespace was added.
    pub tool_name: String,
    /// Position in the host slice used for this snapshot; routing never searches mutable metadata.
    pub(crate) host_index: usize,
}

/// Rejects ambiguous model-facing names after all native and plugin definitions are combined.
/// Namespacing can itself collide with a literal name, so validation must inspect final names.
pub fn ensure_unique_tool_names<'a>(
    names: impl IntoIterator<Item = &'a str>,
) -> Result<(), AgentError> {
    let mut seen = std::collections::HashSet::new();
    for name in names {
        if !seen.insert(name) {
            return Err(AgentError::InvalidRequest(format!(
                "duplicate tool name '{name}'"
            )));
        }
    }
    Ok(())
}

/// Resolves every tool declared across the given hosts, keeping provider attribution.
///
/// The result is sorted by tool name and every schema has sorted keys (see [`crate::layout`]).
///
/// Prevents name collision: if multiple plugins declare tools with identical names,
/// they are automatically disambiguated with namespacing (`<plugin_id>__<tool_name>`).
/// Returns an error if a schema has a non-finite number or names remain ambiguous after resolution.
pub fn resolve_tools(hosts: &[Arc<dyn ToolHost>]) -> Result<Vec<ResolvedTool>, AgentError> {
    // Discovery can refresh between calls. Both counting and naming must see one snapshot,
    // and each resolved target retains its source rather than parsing a name during dispatch.
    let snapshots: Vec<_> = hosts
        .iter()
        .map(|host| (host.host_id().to_string(), host.plugin_metas()))
        .collect();
    // 1. First pass: count tool name occurrences across all plugins
    let mut name_counts: std::collections::HashMap<String, usize> =
        std::collections::HashMap::new();
    for (_, metas) in &snapshots {
        for plugin in metas {
            for tool in &plugin.tools {
                *name_counts.entry(tool.name.clone()).or_insert(0) += 1;
            }
        }
    }

    // 2. Second pass: build definitions, namespacing any collided names
    let mut tools = Vec::new();
    for (host_index, (host_id, metas)) in snapshots.into_iter().enumerate() {
        for plugin in &metas {
            for tool in &plugin.tools {
                let parameters = match &tool.parameters {
                    Some(s) => crate::layout::canonical_json(
                        prost_struct_to_json(s.clone()).map_err(|error| {
                            AgentError::InvalidRequest(format!(
                                "invalid plugin tool schema: {error}"
                            ))
                        })?,
                    ),
                    None => serde_json::json!({
                        "type": "object",
                        "properties": {}
                    }),
                };

                let is_duplicate = name_counts.get(&tool.name).copied().unwrap_or(0) > 1;
                let (resolved_name, description) = if is_duplicate {
                    let ns_name = namespaced_tool_name(&plugin.id, &tool.name);
                    tracing::warn!(
                        tool_name = %tool.name,
                        plugin_id = %plugin.id,
                        namespaced = %ns_name,
                        "Duplicate tool name across plugins; disambiguated via namespacing"
                    );
                    (
                        ns_name,
                        format!("{} (plugin: {})", tool.description, plugin.id),
                    )
                } else {
                    (tool.name.clone(), tool.description.clone())
                };

                tools.push(ResolvedTool {
                    definition: ToolDefinition {
                        name: resolved_name,
                        description,
                        parameters,
                    },
                    plugin_id: plugin.id.clone(),
                    host_id: host_id.clone(),
                    tool_name: tool.name.clone(),
                    host_index,
                });
            }
        }
    }

    // One fixed order, whatever the order hosts registered in: the tool list is the very top of the
    // prompt, so a reshuffle there invalidates the provider's cache for the whole request.
    tools.sort_by(|a, b| a.definition.name.cmp(&b.definition.name));
    ensure_unique_tool_names(tools.iter().map(|tool| tool.definition.name.as_str()))?;
    Ok(tools)
}

/// Dynamically aggregates tool definitions declared across all active plugin hosts.
///
/// A thin projection of [`resolve_tools`], which owns the collision rule; keeping one
/// implementation means the console and the model can never disagree about a tool name.
pub fn aggregate_tools(hosts: &[Arc<dyn ToolHost>]) -> Result<Vec<ToolDefinition>, AgentError> {
    Ok(resolve_tools(hosts)?
        .into_iter()
        .map(|tool| tool.definition)
        .collect())
}

/// Central Tool Calling state machine router and execution loop.
///
/// Serves as a specialized adapter around an [`Agent`] for pipeline integration: it projects the
/// agent's result and errors into the shape the pipeline acts on.
#[derive(Clone)]
pub struct ToolRouter {
    agent: Arc<dyn Agent>,
}

impl ToolRouter {
    /// Default maximum reasoning turns allowed to prevent runaway tool loops.
    pub const DEFAULT_MAX_ITERATIONS: usize = 2;

    /// Creates a new `ToolRouter` with default maximum iterations (2 turns).
    pub fn new<M: Memory + 'static>(
        gateway: Arc<dyn LlmProvider>,
        memory: Arc<M>,
        default_model: impl Into<String>,
    ) -> Self {
        let agent = BuiltinAgent::builder("tool_router", gateway)
            .memory(memory as Arc<dyn Memory>)
            .model(default_model)
            .max_iterations(Self::DEFAULT_MAX_ITERATIONS)
            .build();
        Self {
            agent: Arc::new(agent),
        }
    }

    /// Creates a `ToolRouter` wrapping an existing shared [`Agent`].
    pub fn from_arc(agent: Arc<dyn Agent>) -> Self {
        Self { agent }
    }

    /// Creates a `ToolRouter` wrapping an existing [`Agent`].
    pub fn from_agent(agent: impl Agent + 'static) -> Self {
        Self {
            agent: Arc::new(agent),
        }
    }

    /// Returns a reference to the active memory backend.
    pub fn memory(&self) -> &Arc<dyn Memory> {
        self.agent.memory()
    }

    /// Access to the underlying [`Agent`].
    pub fn agent(&self) -> &Arc<dyn Agent> {
        &self.agent
    }

    /// Returns a cloned `Arc` of the underlying [`Agent`] engine.
    pub fn agent_arc(&self) -> Arc<dyn Agent> {
        Arc::clone(&self.agent)
    }

    /// Executes the tool calling loop for an incoming conversational message.
    pub async fn execute(
        &self,
        session_id: &str,
        user_input: &str,
        hosts: &[Arc<dyn ToolHost>],
    ) -> Result<ToolRouterOutput, ToolRouterError> {
        self.map_result(self.agent.run(session_id, user_input, hosts).await)
    }

    /// Executes the tool calling loop for a fully built user message.
    ///
    /// Used by the pipeline so a turn that referenced media reaches the provider with its
    /// multimodal parts intact; plain text callers keep using [`ToolRouter::execute`].
    pub async fn execute_message(
        &self,
        session_id: &str,
        message: crate::gateway::types::ChatMessage,
        hosts: &[Arc<dyn ToolHost>],
    ) -> Result<ToolRouterOutput, ToolRouterError> {
        self.execute_message_with(
            session_id,
            message,
            hosts,
            crate::agent::TurnOptions::default(),
        )
        .await
    }

    /// Executes one turn like [`ToolRouter::execute_message`], with per-turn settings.
    pub async fn execute_message_with(
        &self,
        session_id: &str,
        message: crate::gateway::types::ChatMessage,
        hosts: &[Arc<dyn ToolHost>],
        options: crate::agent::TurnOptions,
    ) -> Result<ToolRouterOutput, ToolRouterError> {
        self.map_result(
            self.agent
                .run_message_with(session_id, message, hosts, options)
                .await,
        )
    }

    /// Projects an agent run result into the router's output type.
    fn map_result(
        &self,
        result: Result<crate::agent::AgentOutput, AgentError>,
    ) -> Result<ToolRouterOutput, ToolRouterError> {
        result.map(|output| ToolRouterOutput {
            content: output.content,
            reasoning: output.reasoning,
            executed_tools: output.executed_tools,
            attachments: output.attachments,
        })
    }
}
